### ISSUE TITLE
How to change FPS Rate

### ISSUE THREAD

**Issue by tazmanyak** [Hotride/UOMod#1]
Hello @Hotride ,

I have used your UOMOD library to path FPS in realy time in my server client. However, FPS Rate is too much and I cannot figure it out how to operate it. In your already built application ( UOPatcher ), when I click on memory fps checkbox, in the game everything looks fine. But when using UOMOD directly by "CPacher", fps rate is overrated. 

If you can help me to manage it, I'll be very pleased.

**Comment by Hotride** [comment]
Hello, Burak Demirsoy!

Show the code, how do you use it?
For correct operation, it is necessary to embed UOMod.dll in the client process so that it can correctly change its memory and instructions.
Injection uomod.dll into client.exe process (runtime) example:  https://github.com/Hotride/UOPatcher/blob/master/MainScript.cpp#L286
  
>Вторник, 24 марта 2020, 10:26 +03:00 от Burak Demirsoy <notifications@github.com>:
> 
> 
>Hello  @Hotride ,
>I have used your UOMOD library to path FPS in realy time in my server client. However, FPS Rate is too much and I cannot figure it out how to operate it. In your already built application ( UOPatcher ), when I click on memory fps checkbox, in the game everything looks fine. But when using UOMOD directly by "CPacher", fps rate is overrated.
>If you can help me to manage it, I'll be very pleased.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Timur.

**Comment by tazmanyak** [comment]
Hello Timur,

![image](https://user-images.githubusercontent.com/1527013/77456037-b8a8fe80-6e0b-11ea-8799-a365a8619e5e.png)

I have my own project for ultima online client connection. I moved necessary classes from UOMod project like the followings:

- FPSPatchASM
- ProcessManager
- PacketInfo
- UOMod

I didnot use dll as it is.

I have my own dll which is attached to client with mutex. From there, I operate your codes and it works fine but with super fast FPS. I can eable to enable and disable FPS without a problem. But could not find any solution for too much FPS problem.

`g_Patcher.Inject();` Inside of the Inject I call Install();

```
void CPatcher::Inject()
{
	if (g_ClientWindowProc == NULL)
	{
		SearchClientHandle();

		if (m_ClientHandle != 0)
		{
			g_ClientWindowProc = (WNDPROC)SetWindowLongPtr(m_ClientHandle, GWL_WNDPROC, (LONG)HookWindowProc);
			g_Patcher.Install();

		}
	}
}
```


I commented some part of t your Patches because I donot want to use it.


```
void CPatcher::FindPatches(PBYTE data, int size)
{
	FindFPSPatch(data, size, (CPatchDataFPS*)m_Patches[PT_FPS]);
	//FindStaminaPatch(data, size, m_Patches[PT_STAMINA]);
	//FindAlwaysLightPatch(data, size, (CPatchDataLight*)m_Patches[PT_ALWAYS_LIGHT]);
	//FindPaperdollSlotsPatch(data, size, (CPatchDataPaperdollSlots*)m_Patches[PT_PAPERDOLL_SLOTS]);
	//FindOptionsNotificationPatch(data, size, m_Patches[PT_OPTIONS_NOTIFICATION]);
	//FindViewRangePatch(data, size, (CPatchDataViewRange*)m_Patches[PT_VIEW_RANGE]);
	//FindGMStepPatch(data, size, (CPatchDataViewRange*)m_Patches[PT_GM_STEP]);
}
```

Lastly, I have exported a method for FPS ;

`DLLFUNCTION void SetFPS(HWND client, bool state)
{
	g_Patcher.SetPatch(state, client, 1);
}`

I did realize that you are using PM_ENABLE for enabling and PT_FPS for which package to path.

Everything is okay and fine but it is super fast. I recorded a short video to get you understand about what the problem is. I uploaded to Google Drive like the following :

https://drive.google.com/open?id=1LzkhhgWw8i_IMoUIqj9nIMXWG4JnFJEO

Thanks in advance,

Burak

**Comment by Hotride** [comment]
Burak!

Yes, this behavior may be due to the fact that the download address of the AnimInfo.mul file was not found in the client's memory.
Make sure that the addresses for the FPS patch are correct and that during the application of the patch all the necessary data in the client is replaced.
This can be checked either by debugging your dll, outputting debugging information to the debug output/file, or a memory editor in CheatEngine (or any other process monitor).

**Comment by tazmanyak** [comment]
Hello Timur,

I did realise that I commented "animinfo" part, I removed all comments and make g_patcher.Install() like the following;


```
void CPatcher::Install()
{
 	s_ClientPath = "C:\\Program Files (x86)\\EA Games\\Ultima Online 2D Client\\tnsclient6.dll";
	if (m_Initalized)
		return;

	SearchClientHandle();

	if (m_ClientHandle == 0)
	{
		MessageBox(NULL, "Client window not found", "Error", MB_OK);
		return;
	}

	if (g_ProcessManager.Open(m_ClientHandle))
	{
	/*	char clientExePath[MAX_PATH] = { 0 };
		GetModuleFileNameA(NULL, clientExePath, MAX_PATH);
		LPSTR clientPath = {};
		GetFinalPathNameByHandleA(m_ClientHandle, clientPath, 500, FILE_NAME_OPENED);*/
		FILE *file = NULL;
		fopen_s(&file, s_ClientPath.c_str(), "rb");

		if (file != NULL)
		{
			fseek(file, 0, SEEK_END);
			int fileSize = ftell(file);
			fseek(file, 0, SEEK_SET);

			std::vector<BYTE> fileData(fileSize, 0);

			fread(&fileData[0], 1, fileSize, file);

			fclose(file);

			if (fileSize > 100)
			{
				FindPatches(&fileData[0], fileSize);

				/*char *bf = strchr(const_cast<char *>(s_ClientPath.c_str()), '\\');

				if (bf)
					*bf = 0;*/
				std::string uoPath = s_ClientPath.replace(s_ClientPath.find("tnsclient6.dll"), 14 , "");;
				std::string animinfo = uoPath + "Animinfo.mul";

				fopen_s(&file, animinfo.c_str(), "rb");

				if (file != NULL)
				{
					fseek(file, 0, SEEK_END);
					CPatchDataFPS *fpsPatch = (CPatchDataFPS*)m_Patches[PT_FPS];
					fpsPatch->DataSize = ftell(file);

					fclose(file);

					if (fpsPatch->Found && g_FPS_FunctionPointer != 0)
					{
						DWORD VPTmp = 0;
						VirtualProtect((PVOID)fpsPatch->AddressOfCutting, 5, PAGE_EXECUTE_READWRITE, &VPTmp);
						DWORD MemoryData = fpsPatch->AddressOfCutting;
						*(PBYTE)MemoryData = 0xE9;
						MemoryData = fpsPatch->AddressOfCutting + 1;
						*(PDWORD)MemoryData = (DWORD)FixFPS - fpsPatch->AddressOfCutting - 5;
					}
					else
						fpsPatch->Found = false;

					WNDCLASSEX wcex = { 0 };
					wcex.cbSize = sizeof(WNDCLASSEX);
					wcex.style = CS_HREDRAW | CS_VREDRAW;
					wcex.lpfnWndProc = WindowProc;
					wcex.cbClsExtra = 0;
					wcex.cbWndExtra = 0;
					wcex.hInstance = NULL; // hinstance;
					wcex.hCursor = NULL;
					wcex.hbrBackground = NULL;
					wcex.lpszMenuName = NULL;
					LPSTR className = { 0 };
					wsprintf(className, "UOModWindow_%08X", m_ClientHandle);
					wcex.lpszClassName = className;
					wcex.hIconSm = NULL;

					RegisterClassEx(&wcex);

					m_Handle = CreateWindow(className, className, WS_OVERLAPPEDWINDOW, 0, 0, 100, 20, NULL, NULL, /*hinstance*/NULL, NULL);

					m_Initalized = (m_Handle != NULL);

					if (!m_Initalized)
						MessageBox(NULL, "Failed to create window", "Error", MB_OK);
				}
				else
					MessageBoxA(NULL, ("File not found:\n" + animinfo).c_str(), "Error", MB_OK);
			}
		}
		else
			MessageBox(NULL, "Client.exe not found", "Error", MB_OK);
	}
	else
		MessageBox(NULL, "Failed to open process.", "Error", MB_OK);
}
```

On this line : 
`*(PBYTE)MemoryData = 0xE9;`

I'm getting the following error :

![image](https://user-images.githubusercontent.com/1527013/77559493-51538300-6ecd-11ea-8205-5647818bcc02.png)


I'm opening process without getting any error. What could it be the reason ? 

Thanks, 

Burak

**Comment by Hotride** [comment]
Burak,

Need to check if the client (tnsclient6.dll) is really loading at the base address 0x00400000 or is the base address different?
If it is different, then the patcher is trying to patch the wrong piece of memory.
The original client is always loaded at 0x00400000 (base image address) and the patcher is tuned to this address.

**Comment by tazmanyak** [comment]
Hello Timur,

Is it work for you if I ask you for "skype" meeting, and I can give you TeamViewer so that you can look at. Because your UOPacher.exe working fine with my client, however when I used your UOMod.dll's code, it always says access violation. 

My skype : "burak.demirsoy"

Thanks for your support in advance,

Burak,

**Comment by Hotride** [comment]
Burak,

You are not visible to me on Skype.
Try to find me: hotridee
